### ISSUE TITLE
Name for our dimension?

### ISSUE THREAD

**Issue by Singularius** [IndustrialScienceTeam/AncientPower#18]
We should thin about a name for our dimension so we dont always have to talk about "our dimension" or "the new dimension".

My proposals are:
- "The Calculus" because our dimension is mainly stone and "calculus" sounds cooler than "stone" or "rock"
- "The Extinct Realm" because our mod revolves around the idea of an extinct civilization that used to live in the dimension
- "The Bleak Lands", hinting that our dimension is not as lush as the overworld and life can sometimes be hard in it.

Tell me about your ideas or whether you like one of mine or not.

**Comment by Finesim97** [comment]
I like "The Calculus"

**Comment by Finesim97** [comment]
At the moment i think we should go with "The Extinct Realm", because The calculus also is word for a calculation stone
